from app.app import create_app
from app.new_posts.models import Articles
from app.extensions.database import db
import datetime

app = create_app()
app.app_context().push()

blog_posts_data = {
    'my-first-post':{   'text': 'test1 test1 test1 test1 test1 test1', 
                        'description': 'test1 test1 test1', 
                        'title': 'my first post',
                        'category': 'test',
                        'created_at': datetime.datetime(2020, 1, 1),
                        'author': 'author 1' },
    'my-second-post':{  'text': 'test2 test2 test2 test2 test2 test2',
                        'description': 'test2 test2 test2',
                        'title': 'my second post',
                        'category': 'test',
                        'created_at': datetime.datetime(2020, 1, 1),
                        'author': 'author 2' },
    'my-third-post':{   'text': 'test3 test3 test3 test3 test3 test3',
                        'description': 'test3 test3 test3',
                        'title': 'my third post',
                        'category': 'test',
                        'created_at': datetime.datetime(2020, 1, 1),
                        'author': 'author 3' },
    'my-fourth-post':{  'text': 'test4 test4 test4 test4 test4 test4',
                        'description': 'test4 test4 test4',
                        'title': 'my fourth post',
                        'category': 'test',
                        'created_at': datetime.datetime(2020, 1, 1),
                        'author': 'author 4' },
    'my-fifth-post':{   'text': 'test5 test5 test5 test5 test5 test5',
                        'description': 'test5 test5 test5',
                        'title': 'my fifth post',
                        'category': 'test',
                        'created_at': datetime.datetime(2020, 1, 1),
                        'author': 'author 5' },
    'my-sixth-post':{   'text': 'test6 test6 test6 test6 test6 test6',
                        'description': 'test6 test6 test6',
                        'title': 'my sixth post',
                        'category': 'test',
                        'created_at': datetime.datetime(2020, 1, 1),
                        'author': 'author 6' },
    'my-seventh-post':{ 'text': 'test7 test7 test7 test7 test7 test7',
                        'description': 'test7 test7 test7',
                        'title': 'my seventh post',
                        'category': 'test',
                        'created_at': datetime.datetime(2020, 1, 1),
                        'author': 'author 7' },
    'my-eighth-post':{   'text': 'test8 test8 test8 test8 test8 test8',
                        'description': 'test8 test8 test8',
                        'title': 'my eighth post',
                        'category': 'test',
                        'created_at': datetime.datetime(2020, 1, 1),
                        'author': 'author 8' },
    'my-ninth-post':{   'text': 'test9 test9 test9 test9 test9 test9',
                        'description': 'test9 test9 test9',
                        'title': 'my ninth post',
                        'category': 'test',
                        'created_at': datetime.datetime(2020, 1, 1),
                        'author': 'author 9' },
    'my-tenth-post':{   'text': 'test10 test10 test10 test10 test10 test10',
                        'description': 'test10 test10 test10',
                        'title': 'my tenth post',
                        'category': 'test',
                        'created_at': datetime.datetime(2020, 1, 1),
                        'author': 'author 10' },
    'my-eleventh-post':{'text': 'test11 test11 test11 test11 test11 test11',
                        'description': 'test11 test11 test11',
                        'title': 'my eleventh post',
                        'category': 'test',
                        'created_at': datetime.datetime(2020, 1, 1),
                        'author': 'author 11' },
    'my-twelfth-post':{ 'text': 'test12 test12 test12 test12 test12 test12',
                        'description': 'test12 test12 test12',
                        'title': 'my twelfth post',
                        'category': 'test',
                        'created_at': datetime.datetime(2020, 1, 1),
                        'author': 'author 12' },
    'my-thirteenth-post':{'text': 'test13 test13 test13 test13 test13 test13',
                        'description': 'test13 test13 test13',
                        'title': 'my thirteenth post',
                        'category': 'test',
                        'created_at': datetime.datetime(2020, 1, 1),
                        'author': 'author 13' },
    'my-fourteenth-post':{'text': 'test14 test14 test14 test14 test14 test14',
                        'description': 'test14 test14 test14',
                        'title': 'my fourteenth post',
                        'category': 'test',
                        'created_at': datetime.datetime(2020, 1, 1),
                        'author': 'author 14' },
    'my-fifteenth-post':{'text': 'test15 test15 test15 test15 test15 test15',
                        'description': 'test15 test15 test15',
                        'title': 'my fifteenth post',
                        'category': 'test',
                        'created_at': datetime.datetime(2020, 1, 1),
                        'author': 'author 15' },
    'my-sixteenth-post':{'text': 'test16 test16 test16 test16 test16 test16',
                        'description': 'test16 test16 test16',
                        'title': 'my sixteenth post',
                        'category': 'test',
                        'created_at': datetime.datetime(2020, 1, 1),
                        'author': 'author 16' },
    'my-seventeenth-post':{'text': 'test17 test17 test17 test17 test17 test17',
                        'description': 'test17 test17 test17',
                        'title': 'my seventeenth post',
                        'category': 'test',
                        'created_at': datetime.datetime(2020, 1, 1),
                        'author': 'author 17' },
    'my-eighteenth-post':{'text': 'test18 test18 test18 test18 test18 test18',
                        'description': 'test18 test18 test18',
                        'title': 'my eighteenth post',
                        'category': 'test',
                        'created_at': datetime.datetime(2020, 1, 1),
                        'author': 'author 18' }}           

for slug, blog_post in blog_posts_data.items():
    new_blog_post = Articles(slug=slug, text=blog_post['text'], description=blog_post['description'], title=blog_post['title'], category=blog_post['category'], created_at=blog_post['created_at'], author=blog_post['author'])

    db.session.add(new_blog_post)

db.session.commit()